[project]
authors = ["Daniel Tollenaar <daniel@d2hydro.nl>"]
channels = ["conda-forge"]
description = "Web viewer for Ribasim models."
name = "hydrobase"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
app = "python -m uvicorn web:app --reload --host 127.0.0.1 --port 3000"

[dependencies]
fastapi = "*"
jinja2 = "*"
uvicorn = "*"
jupyterlab = "*"
httpx = "*"
geopandas = "*"
pyogrio = "*"
ribasim = "*"
