name: hydrobase

channels:
  - conda-forge
  - defaults

dependencies:
  - aiofiles
  - fastapi
  - git
  - uvicorn
  - pandas
  - geopandas
  - shapely
  - rasterio
  - requests
  - sqlalchemy
  - psycopg2
